dddrrrrrrrrrrrrrrr
dddrrrrrrrrrrrrrrr
;;;;;;;;;;;;;;;;;;;;;;
with out aut all
about to send test email to me 
this si profile  {'id': 1, 'name': OrderedDict([('id', 4), ('likedposts', []), ('role', 'hospital'), ('first_name', 'AbbasMedico'), ('last_name', 'khan'), ('profilepic', '/media/images/default.jpg'), ('email', 'asifkhan15848@gmail.com'), ('post_count', 0), ('follower_count', 0), ('following_count', 0), ('userlikes', 0)]), 'galleries': [OrderedDict([('id', 1), ('image', '/media/hospitalgallery/5_2qjItj8.jpeg'), ('caption', 'new'), ('hospital', 1)])], 'services': [], 'affiliated_dr': [], 'is_deleted': False, 'profpic': '/media/images/default.jpg', 'address': None, 'city': None, 'state': None, 'country': None, 'phone_number': None, 'mobile': None, 'email': 'asifkhan15848@gmail.com', 'website': None, 'description': None, 'created_at': '2023-06-12T17:25:53.984704Z', 'updated_at': '2023-06-12T17:25:53.987358Z', 'departments': []}
this is uid NA
this is token bq6csf-57ae02abaf962ffae80bfb3cfb27564b
https://vmclub.a2zcyberpark.com/resetEpassword/NA/bq6csf-57ae02abaf962ffae80bfb3cfb27564b
dddddddddddddddddddd
this is pt sani khan
<QueryDict: {'visit_type': ['revisit'], 'scheduled_time': ['2023-06-22T07:50'], 'duration': ['3'], 'reason': ['dfas'], 'history': ['dd'], 'patient': [2], 'doctor': [1]}>
ooooooooooooooooooo
sending appointment email admin@gmail.com sani18@gmail.com
sending dr email
3
before send <django.core.mail.message.EmailMultiAlternatives object at 0x2ac4c9d0aaf0>
Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/logfile.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a2zcyber/vmc.a2zcyberpark.com/vmc/passenger_wsgi.py", line 12, in <module>
    application = get_wsgi_application()
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 564, in configure
Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 745, in configure_handler
    handler = self.configure_handler(handlers[name])
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1146, in __init__
    result = factory(**kwargs)
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
    StreamHandler.__init__(self, self._open())
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1175, in _open
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/logfile.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a2zcyber/vmc.a2zcyberpark.com/vmc/passenger_wsgi.py", line 12, in <module>
    application = get_wsgi_application()
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    return open(self.baseFilename, self.mode, encoding=self.encoding,
    django.setup(set_prefix=False)
PermissionError: [Errno 13] Permission denied: '/logfile.log'
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a2zcyber/vmc.a2zcyberpark.com/vmc/passenger_wsgi.py", line 12, in <module>
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/utils/log.py", line 76, in configure_logging
    application = get_wsgi_application()
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    logging_config_func(logging_settings)
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 809, in dictConfig
    django.setup(set_prefix=False)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
    dictConfigClass(config).configure()
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/logfile.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a2zcyber/vmc.a2zcyberpark.com/vmc/passenger_wsgi.py", line 12, in <module>
    application = get_wsgi_application()
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1146, in __init__
Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 564, in configure
    StreamHandler.__init__(self, self._open())
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1175, in _open
    handler = self.configure_handler(handlers[name])
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 745, in configure_handler
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/logfile.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a2zcyber/vmc.a2zcyberpark.com/vmc/passenger_wsgi.py", line 12, in <module>
    application = get_wsgi_application()
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
    result = factory(**kwargs)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1146, in __init__
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 571, in configure
    StreamHandler.__init__(self, self._open())
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1175, in _open
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/logfile.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a2zcyber/vmc.a2zcyberpark.com/vmc/passenger_wsgi.py", line 12, in <module>
    application = get_wsgi_application()
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/logfile.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a2zcyber/vmc.a2zcyberpark.com/vmc/passenger_wsgi.py", line 12, in <module>
    application = get_wsgi_application()
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/alt/python39/lib64/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/logfile.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a2zcyber/vmc.a2zcyberpark.com/vmc/passenger_wsgi.py", line 12, in <module>
    application = get_wsgi_application()
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/a2zcyber/virtualenv/vmc.a2zcyberpark.com/vmc/3.9/lib/python3.9/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/alt/python39/lib64/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
with out aut all
dddrrrrrrrrrrrrrrr
dddrrrrrrrrrrrrrrr
dddddddddddddddddddd
this is pt sani khan
<QueryDict: {'visit_type': ['revisit'], 'scheduled_time': ['2023-06-22T07:54'], 'duration': ['3'], 'reason': ['i ma feeling tired'], 'history': ['dfasdf'], 'patient': [2], 'doctor': [1]}>
ooooooooooooooooooo
sending appointment email admin@gmail.com sani18@gmail.com
sending dr email
3
before send <django.core.mail.message.EmailMultiAlternatives object at 0x2b279ba77b80>
{'id': 1, 'likedposts': [1, 2, 3], 'role': 'doctor', 'first_name': 'admin', 'last_name': 'khan', 'profilepic': '/media/dr_profile_pics/file.PNG', 'email': 'admin@gmail.com', 'post_count': 3, 'follower_count': 0, 'following_count': 0, 'userlikes': 3} pppp
dddrrrrrrrrrrrrrrr
dddrrrrrrrrrrrrrrr
dddddddddddddddddddd
this is pt sani khan
<QueryDict: {'visit_type': ['revisit'], 'scheduled_time': ['2023-05-31T07:56'], 'duration': ['3'], 'reason': ['i am sick'], 'history': ['sdfa'], 'patient': [2], 'doctor': [1]}>
ooooooooooooooooooo
sending appointment email admin@gmail.com sani18@gmail.com
sending dr email
3
before send <django.core.mail.message.EmailMultiAlternatives object at 0x2ba6c1ebdaf0>
after send <django.core.mail.message.EmailMultiAlternatives object at 0x2ba6c1ebdaf0>
dddrrrrrrrrrrrrrrr
dddrrrrrrrrrrrrrrr
dddddddddddddddddddd
this is pt imran khan
<QueryDict: {'scheduled_time': ['2023-06-22T07:02'], 'duration': ['4'], 'reason': ['this is me'], 'history': ['kjasdhfk'], 'patient': [3], 'doctor': [1]}>
ooooooooooooooooooo
sending appointment email admin@gmail.com ak9360575@gmail.com
sending dr email
3
before send <django.core.mail.message.EmailMultiAlternatives object at 0x2b6dce60dac0>
after send <django.core.mail.message.EmailMultiAlternatives object at 0x2b6dce60dac0>
dddrrrrrrrrrrrrrrr
<QueryDict: {'first_name': ['imran'], 'last_name': ['khan'], 'email': ['ak9360575@gmail.com'], 'password': ['kilokhan'], 'password1': ['kilokhan'], 'role': ['patient']}>
this is patient , imran khan
this is user imran khan
dddrrrrrrrrrrrrrrr
dddrrrrrrrrrrrrrrr
with out aut all
{'id': 1, 'likedposts': [1, 2, 3], 'role': 'doctor', 'first_name': 'admin', 'last_name': 'khan', 'profilepic': '/media/dr_profile_pics/file.PNG', 'email': 'admin@gmail.com', 'post_count': 3, 'follower_count': 0, 'following_count': 0, 'userlikes': 3} pppp
dddrrrrrrrrrrrrrrr
dddddddddddddddddddd
this is pt imran khan
<QueryDict: {'scheduled_time': ['2023-06-22T08:05'], 'duration': ['45'], 'reason': ['ljasdlfkjkla'], 'history': ['kklsdlf'], 'patient': [3], 'doctor': [1]}>
ooooooooooooooooooo
sending appointment email admin@gmail.com ak9360575@gmail.com
sending dr email
3
before send <django.core.mail.message.EmailMultiAlternatives object at 0x2b6dce60ea90>
after send <django.core.mail.message.EmailMultiAlternatives object at 0x2b6dce60ea90>
dddrrrrrrrrrrrrrrr
dddrrrrrrrrrrrrrrr
dddddddddddddddddddd
this is pt imran khan
<QueryDict: {'scheduled_time': ['2023-06-22T08:07'], 'duration': ['45'], 'reason': ['i ma feeling tired'], 'history': ['er'], 'patient': [3], 'doctor': [1]}>
ooooooooooooooooooo
sending appointment email admin@gmail.com ak9360575@gmail.com
sending dr email
3
before send <django.core.mail.message.EmailMultiAlternatives object at 0x2b609ef07a90>
after send
patinet email
sending patient email
patinet email has been sended
dddrrrrrrrrrrrrrrr
with out aut all
imran khan
imran khan
<QuerySet [<Appointment:  Dr.admin khan  pt imran khan i ma feeling tired>, <Appointment:  Dr.admin khan  pt imran khan ljasdlfkjkla>, <Appointment:  Dr.admin khan  pt imran khan this is me>]>
with out aut all
dddddddddddddddddddd
this is pt imran khan
<QueryDict: {'scheduled_time': ['2023-06-22T08:11'], 'duration': ['5'], 'reason': ['Hehvsvd'], 'history': ['Hshehs'], 'patient': [3], 'doctor': [1]}>
ooooooooooooooooooo
sending appointment email admin@gmail.com ak9360575@gmail.com
sending dr email
3
before send <django.core.mail.message.EmailMultiAlternatives object at 0x2acfea435b20>
after send
patinet email
sending patient email
patinet email has been sended
dddrrrrrrrrrrrrrrr
dddrrrrrrrrrrrrrrr
{'id': 1, 'likedposts': [1, 2, 3], 'role': 'doctor', 'first_name': 'admin', 'last_name': 'khan', 'profilepic': '/media/dr_profile_pics/file.PNG', 'email': 'admin@gmail.com', 'post_count': 3, 'follower_count': 0, 'following_count': 0, 'userlikes': 3} pppp
dddrrrrrrrrrrrrrrr
dddrrrrrrrrrrrrrrr
dddrrrrrrrrrrrrrrr
with out aut all
dddrrrrrrrrrrrrrrr
 Dr.admin khan  pt imran khan Hehvsvd admin khan
<QueryDict: {'status': ['scheduled']}>
patinet update
sendign patine tupdate
patient update email has been sended
 Dr.admin khan  pt imran khan i ma feeling tired admin khan
<QueryDict: {'status': ['scheduled']}>
patinet update
sendign patine tupdate
patient update email has been sended
imran khan
imran khan
<QuerySet [<Appointment:  Dr.admin khan  pt imran khan Hehvsvd>, <Appointment:  Dr.admin khan  pt imran khan i ma feeling tired>, <Appointment:  Dr.admin khan  pt imran khan ljasdlfkjkla>, <Appointment:  Dr.admin khan  pt imran khan this is me>]>
with out aut all
dddrrrrrrrrrrrrrrr
